version: "3.9"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: energy_forecast
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
