name: Ingest CAISO and Weather Data

on:
  workflow_dispatch:     # Manual trigger
  schedule:
    - cron: "0 6 * * *"  # Run daily at 6 AM UTC

jobs:
  ingest:
    runs-on: ubuntu-22.04  # Stable and supported

    env:
      PGHOST: ${{ secrets.PGHOST }}
      PGPORT: ${{ secrets.PGPORT }}
      PGDATABASE: ${{ secrets.PGDATABASE }}
      PGUSER: ${{ secrets.PGUSER }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CAISO ingestion
        run: |
          PYTHONPATH=. python src/fetch_caiso.py

      - name: Run weather ingestion
        run: |
          PYTHONPATH=. python src/fetch_weather.py
