name: Ingest CAISO and Weather Data

on:
  schedule:
    - cron: "0 6 * * *"  # Every day at 6 AM UTC
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run CAISO ingestion
        run: |
          PYTHONPATH=. python3 src/fetch_caiso.py

      - name: Run weather ingestion
        run: |
          PYTHONPATH=. python3 src/fetch_weather.py
